backend:
name: git-gateway
branch: main
media_folder: "public/assets/blog" 
public_folder: "/assets/blog" 
collections:
-name: "blog"
label: "blog"
folder: "src/blog"
create: true
slug: "blog/{{year}}/{{month}}/{{slug}}"
fields:
- {label: "Title", name: "title", widget: "string"}
- {label: "Description", name: "Description", widget: "string"}
  